/*
 * weatherapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package WeatherAPIClient

import(
	"weatherapi_lib/configuration_pkg"
	"weatherapi_lib/apis_pkg"
)
/*
 * Client structure as interface implementation
 */
type WEATHERAPI_IMPL struct {
     apis apis_pkg.APIS
     config  configuration_pkg.CONFIGURATION
}

/**
     * Access to Configuration
     * @return Returns the Configuration instance
*/
func (me *WEATHERAPI_IMPL) Configuration() configuration_pkg.CONFIGURATION {
    return me.config
}
/**
     * Access to APIs controller
     * @return Returns the APIs() instance
*/
func (me *WEATHERAPI_IMPL) APIs() apis_pkg.APIS {
    if(me.apis) == nil {
        me.apis = apis_pkg.NewAPIS(me.config)
    }
    return me.apis
}

