/*
 * weatherapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package configuration_pkg


/** The base Uri for API calls */
const BASEURI string = "https://api.weatherapi.com/v1"



type CONFIGURATION_IMPL struct {
    /** Replace the value of Key with an appropriate value */
    key string
}

/*
 * Getter function returning key
 */
func (me *CONFIGURATION_IMPL) Key() string{
    return me.key
}

/*
 * Setter function setting up key
 */
func (me *CONFIGURATION_IMPL) SetKey(key string) {
    me.key = key
}

