/*
 * weatherapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package apis_pkg

import "time"
import "weatherapi_lib/configuration_pkg"
import "weatherapi_lib/models_pkg"

/*
 * Interface for the APIS_IMPL
 */
type APIS interface {
    GetRealtimeWeather (string, *string) (*models_pkg.CurrentJsonResponse, error)

    GetForecastWeather (string, int64, *time.Time, *int64, *int64, *string) (*models_pkg.ForecastJsonResponse, error)

    GetHistoryWeather (string, *time.Time, *int64, *time.Time, *int64, *int64, *string) (*models_pkg.HistoryJsonResponse, error)

    SearchAutocompleteWeather (string) ([]*models_pkg.SearchJsonResponse, error)

    GetIpLookup (string) (*models_pkg.IpJsonResponse, error)

    GetTimeZone (string) (*models_pkg.TimezoneJsonResponse, error)

    GetAstronomy (string, *time.Time) (*models_pkg.AstronomyJsonResponse, error)
}

/*
 * Factory for the APIS interaface returning APIS_IMPL
 */
func NewAPIS(config configuration_pkg.CONFIGURATION) *APIS_IMPL {
    client := new(APIS_IMPL)
    client.config = config
    return client
}